#!/usr/bin/env python

from libpldiff import parsers, diff
import optparse
import sys

o_parser = optparse.OptionParser(
    usage="usage: %prog [options] old_file new_file"
)

o_parser.add_option(
    "-f",
    "--format",
    action="store",
    dest="format",
    default="plist",
    help="format of data structure in files"
)
options, args = o_parser.parse_args()

if len(args) != 2:
    o_parser.error("pldiff requires two filepaths as arguments")

parser_cls = parsers.MetaParser.get(options.format)
if not parser_cls:
    o_parser.error("We don't have a parser for '{0}' formats".format(
        options.format
    ))

data_parser = parser_cls()

old_data, new_data = None, None
with open(args[0], 'rb') as f:
    old_data = data_parser.decode(f.read())
with open(args[1], 'rb') as f:
    new_data = data_parser.decode(f.read())

sys.stdout.write(
    data_parser.encode(diff.diff_structures(old_data, new_data))
)